kind: pipeline
name: default

steps:
  - name: docker-build
    image: plugins/docker
    settings:
      repo: stayallive/composer-install
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push
      branch:
        - master
